name: course_env
channels:
  - hcc
  - conda-forge
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - arrow-cpp=21.0.0=hb2ad71a_2
  - aws-c-auth=0.9.0=hb25bd0a_2
  - aws-c-cal=0.9.2=he7b75e1_1
  - aws-c-common=0.12.4=hb03c661_0
  - aws-c-compression=0.3.1=h92c474e_6
  - aws-c-event-stream=0.5.6=h4d13e43_1
  - aws-c-http=0.10.4=hbd4fbc6_1
  - aws-c-io=0.21.4=h88603f0_1
  - aws-c-mqtt=0.13.3=h680d5b3_4
  - aws-c-s3=0.8.7=h3ff94e8_0
  - aws-c-sdkutils=0.2.4=h92c474e_1
  - aws-checksums=0.2.7=h92c474e_2
  - aws-crt-cpp=0.34.0=h7934f7d_0
  - aws-sdk-cpp=1.11.638=hac3f51a_0
  - biopython=1.86=py314h5bd0f2a_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - choreographer=1.2.1=pyhcf101f3_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - deprecated=1.3.1=pyhd8ed1ab_1
  - dorado=0.7.2=h5e1937b_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - gflags=2.2.2=h5888daf_1005
  - glog=0.5.0=h48cff8f_0
  - htslib=1.23=h566b1c6_0
  - icu=78.2=h33c6efd_0
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - k8=1.2=he8db53b_6
  - kernel-headers_linux-64=5.14.0=he073ed8_3
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libabseil=20250814.1=cxx17_hee66210_0
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.11.0=5_h0358290_openblas
  - libcurl=8.18.0=h4e3cde8_0
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - libgrpc=1.74.1=ha2a6211_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.2=hb03c661_0
  - liblzma-devel=5.8.2=hb03c661_0
  - libmpdec=4.0.0=hb03c661_1
  - libnghttp2=1.67.0=had1ee68_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libpng=1.6.54=h421ea60_0
  - libprotobuf=6.33.0=he382b67_0
  - libre2-11=2025.11.05=h3218f0b_0
  - libsqlite=3.51.2=hf4e2dac_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libthrift=0.22.0=h454ac66_1
  - libuuid=2.41.3=h5347b49_0
  - libzlib=1.3.1=hb9d3cd8_2
  - logistro=2.0.1=pyhcf101f3_0
  - lz4-c=1.9.4=hcb278e6_0
  - minimap2=2.30=h577a1d6_0
  - nanofilt=2.8.0=py_0
  - nanoget=1.19.4=pyhdfd78af_0
  - nanomath=1.4.0=pyhdfd78af_0
  - nanoplot=1.46.2=pyhdfd78af_0
  - narwhals=2.15.0=pyhcf101f3_0
  - ncurses=6.5=h2d0b736_3
  - numpy=2.4.1=py314h2b28147_0
  - openssl=3.6.1=h35e630c_1
  - orc=2.2.0=h13e6d3f_1
  - orjson=3.11.5=py314h3b757c3_0
  - packaging=26.0=pyhcf101f3_0
  - pandas=3.0.0=py314hb4ffadd_0
  - pip=26.0=pyh145f28c_0
  - plotly=6.5.2=pyhd8ed1ab_0
  - pluggy=1.6.0=pyhf9edf01_1
  - pyarrow=21.0.0=py314h973aee8_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysam=0.23.3=py314h666adb2_0
  - pytest=9.0.2=pyhcf101f3_0
  - pytest-timeout=2.4.0=pyhd8ed1ab_0
  - python=3.14.2=h32b2ec7_101_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-kaleido=1.2.0=pyhcf101f3_0
  - python_abi=3.14=8_cp314
  - re2=2025.11.05=h6b3e72e_0
  - readline=8.3=h853b02a_0
  - s2n=1.5.25=h5ac9029_1
  - samtools=1.23=h96c455f_0
  - scipy=1.17.0=py314hf07bd8e_1
  - seqtk=1.5=h577a1d6_1
  - simplejson=3.20.2=py314h5bd0f2a_1
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - sysroot_linux-64=2.34=h087de78_3
  - tk=8.6.13=noxft_h366c992_103
  - tomli=2.4.0=pyhcf101f3_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - utf8proc=2.6.1=h5eee18b_1
  - vsearch=2.30.4=hd6d6fdc_0
  - wrapt=2.0.1=py314h5bd0f2a_1
  - xz=5.8.2=ha02ee65_0
  - xz-gpl-tools=5.8.2=ha02ee65_0
  - xz-tools=5.8.2=hb03c661_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb78ec9c_6
prefix: /home/bioc1874/Bioinfo_tools/envs/course_env
